services:
  hapi:
    image: registry.hub.docker.com/hapiproject/hapi:v7.2.0
    ports:
      - "8080:8080"
    environment:
      - hapi.fhir.fhir_version=R4
      - hapi.fhir.bulk_export_enabled=true
      - hapi.fhir.binary_storage_enabled=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:HAPI_PORT/fhir/metadata"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
